# Generated by Django 5.2.3 on 2025-06-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="file",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="path",
            field=models.TextField(default="uploads/"),
        ),
        migrations.AlterField(
            model_name="chunk",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="ai_chat.uploadedfile",
            ),
        ),
    ]
