# Generated by Django 5.2.3 on 2025-06-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0002_remove_uploadedfile_file_uploadedfile_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="path",
            field=models.TextField(default="uploads"),
        ),
    ]
