# Generated by Django 5.2.3 on 2025-07-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_chat", "0003_alter_uploadedfile_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
    ]
